services:
  timemanager:
    build:
      context: ./TimeManager
    container_name: timemanager
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - ./TimeManager/.env

  parser:
    build:
      context: ./parser
    container_name: parser
    ports:
      - "9000:9000"
    depends_on:
      - db
      - redis
    env_file:
      - ./parser/.env
  worker:
    build:
      context: ./parser
    container_name: parser-worker
    command: celery -A worker.celery_app worker --loglevel=info
    depends_on:
      - parser
      - redis
      - db
    env_file:
      - .env
  db:
    image: "postgres:17.2"
    container_name: postgres
    restart: always
    env_file:
      - .env
  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"

